### ISSUE TITLE
Update to OpenAPI generator version 5.3.0

### ISSUE THREAD

**Issue by ariesclark** [vrchatapi/vrchatapi-rust#1]
Blocked by OpenAPITools/openapi-generator#10720

**Comment by ariesclark** [comment]
It seems like the issue was resolved upstream, can we now update the generator? @Foorack

**Comment by C0D3-M4513R** [comment]
I think this can be closed, seeing as `openapi-generator-cli` is on version `6.2.1` in the `ci.yaml` and `openapitools.json`, right?

Seems like commit [4da9bad](https://github.com/vrchatapi/vrchatapi-rust/commit/4da9badb69d3fe8b860d471529f405404dae805b) solved this, right?

**Comment by Foorack** [comment]
Yes, thank you @C0D3-M4513R
